name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Publish lib
        run: deno publish -c ./packages/lib/deno.json
      - name: Publish checkbox
        run: deno publish -c ./packages/checkbox/deno.json
