name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        package: ["lib", "accordion", "angle-slider", "avatar", "checkbox"]
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Publish ${{matrix.package}}
        run: deno publish -c ./packages/${{matrix.package}}/deno.json
